version: '3.8'

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: postgres-test-e2e
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/data/postgres
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
    driver: local

networks:
  test-network:
    driver: bridge