name: Run Tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          check-latest: true

      - name: Upgrade npm
        run: npm install -g npm@9.8.1

      - name: Install dependencies with retry
        run: |
          retry_count=0
          max_retries=3
          until [ $retry_count -ge $max_retries ]
          do
            npm ci --include=dev && break
            retry_count=$((retry_count+1))
            echo "Retrying npm install ($retry_count/$max_retries)..."
            sleep 5
          done

      - name: Upload npm debug log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: npm-debug-log
          path: /home/runner/.npm/_logs/

      - name: Install Prisma CLI
        run: npm install -g prisma

      - name: Generate Prisma client
        run: npm run prisma:generate

      - name: Run tests
        run: npm run test:unit
